# Generated by Django 5.0.6 on 2024-08-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_remove_albom_songs_song_albom'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
            preserve_default=False,
        ),
    ]
