# Generated by Django 5.0.6 on 2024-08-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_albom_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='spotify.albom'),
        ),
    ]
